#!/bin/bash
# ------------------------------------------------------------------------------
# Description:
#
#   This is the driver for the individual script or tool.
#
# Authors:
#
#   Li Dong
# ------------------------------------------------------------------------------

source $GEODIAG_UTILS/geodiag_cmd_utils.sh

# TODO: construct a framework for handling subcommands
case $1 in
"update")
    # for users who are not familiar with git
    cd $GEODIAG_ROOT
    git pull
    exit $?
    ;;
esac

# source the driver for each phenomenon
for driver in $(find $GEODIAG_ROOT/scripts -name "driver.sh"); do
    source $driver
done

notice "Which phenomenon do you want to diagnose?"
read -p "[phenomenon] > " phenon

# call corresponding driver
res=$(find $GEODIAG_ROOT -type d -name "$phenon")
if [[ "$res" == ""  ]] ; then
    report_error "Unknown phenomenon!"
fi
${phenon}_driver
