load "$GEODIAG_TOOLS/utils/lib_message.ncl"
load "$GEODIAG_TOOLS/utils/lib_deg_rad_conversion.ncl"
load "$GEODIAG_TOOLS/utils/lib_data_file.ncl"
load "$GEODIAG_TOOLS/utils/lib_select_region.ncl"
load "$GEODIAG_TOOLS/utils/lib_check_cmd_arg.ncl"
load "$GEODIAG_TOOLS/utils/lib_select_season.ncl"
load "$GEODIAG_TOOLS/utils/lib_calc_lat_bnds.ncl"
load "$GEODIAG_TOOLS/utils/lib_calc_lat_wgts.ncl"

load "$GEODIAG_TOOLS/plot/default_resource.ncl"
load "$GEODIAG_TOOLS/plot/china_map.ncl"
load "$GEODIAG_TOOLS/plot/taylor_diagram.ncl"

load "$GEODIAG_TOOLS/dataset/lib_calc_region_mean.ncl"

load "$GEODIAG_TOOLS/eemd/eemd.ncl"
